### ISSUE TITLE
Seeking assistance with function 'swe_solcross_ut'

### ISSUE THREAD

**Issue by YingChangJ** [krymlov/swe-android-demo#2]
I am currently in the process of trying to locate the function 'swe_solcross_ut'. Could you provide some guidance?

I have successfully integrated various libraries (such as jni-lib, android-lib, java-lib, jyotisa-lib...) using Maven, then included some of these libraries as dependencies in my Android Studio project. (following the libs included in this android demo):
```
dependencies {
    implementation ("swisseph:swe:2.10.03j3c")
    implementation ("swisseph:swe-jyotisa:2.10.03j3c")
    implementation ("swisseph:swe-android:2.10.03j3")}
```
While the calculations of planets are functioning as expected, some of the functions could not be found, like this one: swe_solcross_ut.

On another note, despite adding the jni-lib to the local Maven, I am unsure whether i am utilizing the jni-way or the java-way to employ the function. Currently, I just involves adding the three dependencies and directly using them.

Below is a brief example of how I am implementing them, which closely resembles the provided demo:
```
import swisseph.SweConst
import org.swisseph.SwephNative
import org.swisseph.api.ISweConstants
val sweph = SwephNative(ISweConstants.EPHE_PATH)
        for (p in SweConst.SE_SUN..SweConst.SE_PLUTO) {
            if (p == SweConst.SE_EARTH) continue
            sweph.swe_calc_ut(julianDateNumber, p, SweConst.SEFLG_SPEED, x2, serr)
//...
}
```
Greatly appreciated to your work.

**Comment by krymlov** [comment]
1. you are right, actually none of *cross* API were implemented in Java version of the lib, so, in the JNI version this part is also missed . I think it is ok to add that API to JNI only.

2. SwephNative is JNI-way, but SwissEph is java-way, please check interface ISwissEph

**Comment by YingChangJ** [comment]
Thank you! I found some tutorials about JNI yesterday and managed to add the swe_solcross_ut to the JNI implementation. It's now working successfully.

**Comment by krymlov** [comment]
I have added all *cross* API to JNI
