### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by craigjarman** [krymlov/swe-android-demo#3]
Hi, Are you able to provide some instructions as to how to build this project?
I have tried Android Studio on a Mac, but without success.
Possibly there is a dependency on the swe-android-lib project that is needs to pulled in or manually added. 

Also, what should the **T:/** directory refer to? 

allprojects {
    buildDir = "T:/apps/${rootProject.name}"
}

Thanks

**Comment by krymlov** [comment]
Hi!

> Also, what should the T:/ directory refer to?
it is disk name on Windows OS, you can delete: buildDir = "T:/apps/${rootProject.name}"

> Possibly there is a dependency on the swe-android-lib project that is needs to pulled in or manually added.
Yes, you have to build and install to local maven repo all required dependencies, namelly:
- https://github.com/krymlov/swe-java-lib
- https://github.com/krymlov/swe-jyotisa-lib
- https://github.com/krymlov/swe-android-lib

**Comment by YingChangJ** [comment]
Hi, T is a drive/disk, you should replace this with a real drive you have in your computer, like C or D or something else.
Here are  simple tips for a real newbie (like me:), https://catthethinker.blogspot.com/2023/07/run-swisseph-demo-by-yuriy-krymlov.html
Or, a simpler way is just use the the Krymlov's JNI, which should already covered all the functions of swiss ephemeris, here is a simple demo: https://github.com/YingChangJ/Android_SwissEph_JNI
